### ISSUE TITLE
[bug] A copy of Canvas::RequestThrottle has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#762]
Hi, 

This bug is really annoying. 

It occurs on the stable branch, in dev, each time I modify a controller and refresh the page. 
Any idea? Full trace below:

```ruby
Extracted source (around line #138):
          
  def client_identifier(request)
    request.env['canvas.request_throttle.user_id'] ||= begin
      if token_string = AuthenticationMethods.access_token(request, :GET).presence
        identifier = AccessToken.hashed_token(token_string)
        identifier = "token:#{identifier}"
      elsif identifier = AuthenticationMethods.user_id(request).presence

---

activesupport (4.0.13) lib/active_support/dependencies.rb:446:in `load_missing_constant'
activesupport (4.0.13) lib/active_support/dependencies.rb:184:in `const_missing'
lib/canvas/request_throttle.rb:138:in `client_identifier'
lib/canvas/request_throttle.rb:53:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
app/middleware/request_context_session.rb:25:in `call'
rack (1.5.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.4) lib/rack/session/abstract/id.rb:220:in `call'
encrypted_cookie_store-instructure (1.1.12) lib/encrypted_cookie_store.rb:47:in `call'
app/middleware/sessions_timeout.rb:22:in `call'
app/middleware/load_account.rb:12:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__1122080123040357028__call__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.13) lib/rails/rack/logger.rb:22:in `call'
request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
app/middleware/request_context_generator.rb:49:in `call'
rack (1.5.4) lib/rack/methodoverride.rb:21:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
rack (1.5.4) lib/rack/runtime.rb:17:in `call'
rack (1.5.4) lib/rack/lock.rb:17:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.4) lib/rack/sendfile.rb:112:in `call'
rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:193:in `call'
railties (4.0.13) lib/rails/engine.rb:511:in `call'
railties (4.0.13) lib/rails/application.rb:97:in `call'
rack (1.5.4) lib/rack/content_length.rb:14:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.4) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.4) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.5.4) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.4) lib/rack/server.rb:264:in `start'
railties (4.0.13) lib/rails/commands/server.rb:84:in `start'
railties (4.0.13) lib/rails/commands.rb:76:in `block in <top (required)>'
railties (4.0.13) lib/rails/commands.rb:71:in `tap'
railties (4.0.13) lib/rails/commands.rb:71:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<top (required)>'
spring (1.6.2) lib/spring/client/rails.rb:28:in `load'
spring (1.6.2) lib/spring/client/rails.rb:28:in `call'
spring (1.6.2) lib/spring/client/command.rb:7:in `call'
spring (1.6.2) lib/spring/client.rb:28:in `run'
spring (1.6.2) bin/spring:49:in `<top (required)>'
spring (1.6.2) lib/spring/binstub.rb:11:in `load'
spring (1.6.2) lib/spring/binstub.rb:11:in `<top (required)>'
/home/regmillet/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/regmillet/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
bin/spring:16:in `<top (required)>'
/bin/rails:3:in `load'
/bin/rails:3:in `<main>'
```

**Comment by ccutrer** [comment]
This is fixed in the master branch by https://github.com/instructure/canvas-lms/commit/75b1a5dec55be8b141ba56f28cfa8658d96bc2e6. Since this is only a problem in development, there are no plans to pick it over to the stable branch.

**Comment by Kulgar** [comment]
Ok, that's good to know :)
Thanks @ccutrer

**Comment by beado** [comment]
‏‫من جهاز الـ iPhone الخاص بي‬

**Comment by Kulgar** [comment]
Hmm, still have a similar issue with last master version (as of today): 

```ruby
deadlock; recursive locking

Extracted source (around line #122):
  def self.columns_with_remove_dropped_columns
    @columns_with_dropped ||= self.columns_without_remove_dropped_columns.reject { |c|
      (DROPPED_COLUMNS[self.table_name] || []).include?(c.name)
    }
  end


config/initializers/dropped_columns.rb:122:in `columns_with_remove_dropped_columns'
config/initializers/dropped_columns.rb:129:in `reset_column_information_with_remove_dropped_columns'
config/initializers/switchman.rb:92:in `block (2 levels) in <top (required)>'
config/initializers/switchman.rb:90:in `class_eval'
config/initializers/switchman.rb:90:in `block in <top (required)>'
app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```
